// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppThread.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// EvolutionaryVI
List EvolutionaryVI(arma::field<arma::mat> x, int k, arma::vec n, int N, int p, arma::vec discrete_fields, int n_discrete_fields, arma::vec M, arma::vec continuous_fields, int n_continuous_fields, arma::mat hyper_beta, arma::mat hyper_sigma, arma::vec hyper_phi, arma::vec hyper_tau, arma::vec hyper_delta, double overlap_prob, int n_parents, int n_children, double tol_cavi, int max_iter_cavi, double tol_evi, int max_iter_evi, bool verbose, int n_threads, double max_time, bool custom_initializer, bool use_checkpoint, Nullable<List> initial_values, Nullable<List> checkpoint_values);
RcppExport SEXP _chomper_EvolutionaryVI(SEXP xSEXP, SEXP kSEXP, SEXP nSEXP, SEXP NSEXP, SEXP pSEXP, SEXP discrete_fieldsSEXP, SEXP n_discrete_fieldsSEXP, SEXP MSEXP, SEXP continuous_fieldsSEXP, SEXP n_continuous_fieldsSEXP, SEXP hyper_betaSEXP, SEXP hyper_sigmaSEXP, SEXP hyper_phiSEXP, SEXP hyper_tauSEXP, SEXP hyper_deltaSEXP, SEXP overlap_probSEXP, SEXP n_parentsSEXP, SEXP n_childrenSEXP, SEXP tol_caviSEXP, SEXP max_iter_caviSEXP, SEXP tol_eviSEXP, SEXP max_iter_eviSEXP, SEXP verboseSEXP, SEXP n_threadsSEXP, SEXP max_timeSEXP, SEXP custom_initializerSEXP, SEXP use_checkpointSEXP, SEXP initial_valuesSEXP, SEXP checkpoint_valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type discrete_fields(discrete_fieldsSEXP);
    Rcpp::traits::input_parameter< int >::type n_discrete_fields(n_discrete_fieldsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type continuous_fields(continuous_fieldsSEXP);
    Rcpp::traits::input_parameter< int >::type n_continuous_fields(n_continuous_fieldsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type hyper_beta(hyper_betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type hyper_sigma(hyper_sigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type hyper_phi(hyper_phiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type hyper_tau(hyper_tauSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type hyper_delta(hyper_deltaSEXP);
    Rcpp::traits::input_parameter< double >::type overlap_prob(overlap_probSEXP);
    Rcpp::traits::input_parameter< int >::type n_parents(n_parentsSEXP);
    Rcpp::traits::input_parameter< int >::type n_children(n_childrenSEXP);
    Rcpp::traits::input_parameter< double >::type tol_cavi(tol_caviSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter_cavi(max_iter_caviSEXP);
    Rcpp::traits::input_parameter< double >::type tol_evi(tol_eviSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter_evi(max_iter_eviSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< double >::type max_time(max_timeSEXP);
    Rcpp::traits::input_parameter< bool >::type custom_initializer(custom_initializerSEXP);
    Rcpp::traits::input_parameter< bool >::type use_checkpoint(use_checkpointSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type initial_values(initial_valuesSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type checkpoint_values(checkpoint_valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(EvolutionaryVI(x, k, n, N, p, discrete_fields, n_discrete_fields, M, continuous_fields, n_continuous_fields, hyper_beta, hyper_sigma, hyper_phi, hyper_tau, hyper_delta, overlap_prob, n_parents, n_children, tol_cavi, max_iter_cavi, tol_evi, max_iter_evi, verbose, n_threads, max_time, custom_initializer, use_checkpoint, initial_values, checkpoint_values));
    return rcpp_result_gen;
END_RCPP
}
// MCMC
List MCMC(arma::field<arma::mat> x, int k, arma::vec n, int N, int p, arma::vec discrete_fields, int n_discrete_fields, arma::vec M, arma::vec continuous_fields, int n_continuous_fields, arma::mat hyper_beta, arma::mat hyper_sigma, arma::vec hyper_phi, arma::vec hyper_tau, arma::vec hyper_delta, int n_burnin, int n_gibbs, int n_split_merge, bool verbose, double max_time, bool custom_initializer, bool use_checkpoint, Nullable<List> initial_values, Nullable<List> checkpoint_values);
RcppExport SEXP _chomper_MCMC(SEXP xSEXP, SEXP kSEXP, SEXP nSEXP, SEXP NSEXP, SEXP pSEXP, SEXP discrete_fieldsSEXP, SEXP n_discrete_fieldsSEXP, SEXP MSEXP, SEXP continuous_fieldsSEXP, SEXP n_continuous_fieldsSEXP, SEXP hyper_betaSEXP, SEXP hyper_sigmaSEXP, SEXP hyper_phiSEXP, SEXP hyper_tauSEXP, SEXP hyper_deltaSEXP, SEXP n_burninSEXP, SEXP n_gibbsSEXP, SEXP n_split_mergeSEXP, SEXP verboseSEXP, SEXP max_timeSEXP, SEXP custom_initializerSEXP, SEXP use_checkpointSEXP, SEXP initial_valuesSEXP, SEXP checkpoint_valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type discrete_fields(discrete_fieldsSEXP);
    Rcpp::traits::input_parameter< int >::type n_discrete_fields(n_discrete_fieldsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type continuous_fields(continuous_fieldsSEXP);
    Rcpp::traits::input_parameter< int >::type n_continuous_fields(n_continuous_fieldsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type hyper_beta(hyper_betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type hyper_sigma(hyper_sigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type hyper_phi(hyper_phiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type hyper_tau(hyper_tauSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type hyper_delta(hyper_deltaSEXP);
    Rcpp::traits::input_parameter< int >::type n_burnin(n_burninSEXP);
    Rcpp::traits::input_parameter< int >::type n_gibbs(n_gibbsSEXP);
    Rcpp::traits::input_parameter< int >::type n_split_merge(n_split_mergeSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< double >::type max_time(max_timeSEXP);
    Rcpp::traits::input_parameter< bool >::type custom_initializer(custom_initializerSEXP);
    Rcpp::traits::input_parameter< bool >::type use_checkpoint(use_checkpointSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type initial_values(initial_valuesSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type checkpoint_values(checkpoint_valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(MCMC(x, k, n, N, p, discrete_fields, n_discrete_fields, M, continuous_fields, n_continuous_fields, hyper_beta, hyper_sigma, hyper_phi, hyper_tau, hyper_delta, n_burnin, n_gibbs, n_split_merge, verbose, max_time, custom_initializer, use_checkpoint, initial_values, checkpoint_values));
    return rcpp_result_gen;
END_RCPP
}
// CoordinateAscentVI
List CoordinateAscentVI(arma::field<arma::mat> x, int k, arma::vec n, int N, int p, arma::vec discrete_fields, int n_discrete_fields, arma::vec M, arma::vec continuous_fields, int n_continuous_fields, arma::mat hyper_beta, arma::mat hyper_sigma, arma::vec hyper_phi, arma::vec hyper_tau, arma::vec hyper_delta, double overlap_prob, double tol_cavi, int max_iter_cavi, bool verbose, double max_time, bool custom_initializer, bool use_checkpoint, Nullable<List> initial_values, Nullable<List> checkpoint_values);
RcppExport SEXP _chomper_CoordinateAscentVI(SEXP xSEXP, SEXP kSEXP, SEXP nSEXP, SEXP NSEXP, SEXP pSEXP, SEXP discrete_fieldsSEXP, SEXP n_discrete_fieldsSEXP, SEXP MSEXP, SEXP continuous_fieldsSEXP, SEXP n_continuous_fieldsSEXP, SEXP hyper_betaSEXP, SEXP hyper_sigmaSEXP, SEXP hyper_phiSEXP, SEXP hyper_tauSEXP, SEXP hyper_deltaSEXP, SEXP overlap_probSEXP, SEXP tol_caviSEXP, SEXP max_iter_caviSEXP, SEXP verboseSEXP, SEXP max_timeSEXP, SEXP custom_initializerSEXP, SEXP use_checkpointSEXP, SEXP initial_valuesSEXP, SEXP checkpoint_valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type discrete_fields(discrete_fieldsSEXP);
    Rcpp::traits::input_parameter< int >::type n_discrete_fields(n_discrete_fieldsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type continuous_fields(continuous_fieldsSEXP);
    Rcpp::traits::input_parameter< int >::type n_continuous_fields(n_continuous_fieldsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type hyper_beta(hyper_betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type hyper_sigma(hyper_sigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type hyper_phi(hyper_phiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type hyper_tau(hyper_tauSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type hyper_delta(hyper_deltaSEXP);
    Rcpp::traits::input_parameter< double >::type overlap_prob(overlap_probSEXP);
    Rcpp::traits::input_parameter< double >::type tol_cavi(tol_caviSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter_cavi(max_iter_caviSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< double >::type max_time(max_timeSEXP);
    Rcpp::traits::input_parameter< bool >::type custom_initializer(custom_initializerSEXP);
    Rcpp::traits::input_parameter< bool >::type use_checkpoint(use_checkpointSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type initial_values(initial_valuesSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type checkpoint_values(checkpoint_valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(CoordinateAscentVI(x, k, n, N, p, discrete_fields, n_discrete_fields, M, continuous_fields, n_continuous_fields, hyper_beta, hyper_sigma, hyper_phi, hyper_tau, hyper_delta, overlap_prob, tol_cavi, max_iter_cavi, verbose, max_time, custom_initializer, use_checkpoint, initial_values, checkpoint_values));
    return rcpp_result_gen;
END_RCPP
}
// DIG
List DIG(arma::field<arma::mat> x, int k, arma::vec n, int N, int p, arma::vec discrete_fields, int n_discrete_fields, arma::vec M, arma::vec continuous_fields, int n_continuous_fields, arma::mat hyper_beta, arma::mat hyper_sigma, arma::vec hyper_phi, arma::vec hyper_tau, arma::vec hyper_delta, double decaying_upper_bound, int n_burnin, int n_gibbs, int batch_size, int n_epochs, int n_split_merge, double max_time, bool verbose);
RcppExport SEXP _chomper_DIG(SEXP xSEXP, SEXP kSEXP, SEXP nSEXP, SEXP NSEXP, SEXP pSEXP, SEXP discrete_fieldsSEXP, SEXP n_discrete_fieldsSEXP, SEXP MSEXP, SEXP continuous_fieldsSEXP, SEXP n_continuous_fieldsSEXP, SEXP hyper_betaSEXP, SEXP hyper_sigmaSEXP, SEXP hyper_phiSEXP, SEXP hyper_tauSEXP, SEXP hyper_deltaSEXP, SEXP decaying_upper_boundSEXP, SEXP n_burninSEXP, SEXP n_gibbsSEXP, SEXP batch_sizeSEXP, SEXP n_epochsSEXP, SEXP n_split_mergeSEXP, SEXP max_timeSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type discrete_fields(discrete_fieldsSEXP);
    Rcpp::traits::input_parameter< int >::type n_discrete_fields(n_discrete_fieldsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type continuous_fields(continuous_fieldsSEXP);
    Rcpp::traits::input_parameter< int >::type n_continuous_fields(n_continuous_fieldsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type hyper_beta(hyper_betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type hyper_sigma(hyper_sigmaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type hyper_phi(hyper_phiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type hyper_tau(hyper_tauSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type hyper_delta(hyper_deltaSEXP);
    Rcpp::traits::input_parameter< double >::type decaying_upper_bound(decaying_upper_boundSEXP);
    Rcpp::traits::input_parameter< int >::type n_burnin(n_burninSEXP);
    Rcpp::traits::input_parameter< int >::type n_gibbs(n_gibbsSEXP);
    Rcpp::traits::input_parameter< int >::type batch_size(batch_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type n_epochs(n_epochsSEXP);
    Rcpp::traits::input_parameter< int >::type n_split_merge(n_split_mergeSEXP);
    Rcpp::traits::input_parameter< double >::type max_time(max_timeSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(DIG(x, k, n, N, p, discrete_fields, n_discrete_fields, M, continuous_fields, n_continuous_fields, hyper_beta, hyper_sigma, hyper_phi, hyper_tau, hyper_delta, decaying_upper_bound, n_burnin, n_gibbs, batch_size, n_epochs, n_split_merge, max_time, verbose));
    return rcpp_result_gen;
END_RCPP
}
// psm_vi
arma::mat psm_vi(arma::field<arma::mat> probs_field);
RcppExport SEXP _chomper_psm_vi(SEXP probs_fieldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type probs_field(probs_fieldSEXP);
    rcpp_result_gen = Rcpp::wrap(psm_vi(probs_field));
    return rcpp_result_gen;
END_RCPP
}
// psm_mcmc
arma::mat psm_mcmc(arma::mat samples);
RcppExport SEXP _chomper_psm_mcmc(SEXP samplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type samples(samplesSEXP);
    rcpp_result_gen = Rcpp::wrap(psm_mcmc(samples));
    return rcpp_result_gen;
END_RCPP
}
// flatten_posterior_samples
arma::imat flatten_posterior_samples(arma::field<arma::field<IntegerVector>> samples, int k, int N);
RcppExport SEXP _chomper_flatten_posterior_samples(SEXP samplesSEXP, SEXP kSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::field<IntegerVector>> >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(flatten_posterior_samples(samples, k, N));
    return rcpp_result_gen;
END_RCPP
}
// evaluate_performance
List evaluate_performance(arma::field<IntegerVector> estimation, arma::field<IntegerVector> truth, int N, bool return_matrix);
RcppExport SEXP _chomper_evaluate_performance(SEXP estimationSEXP, SEXP truthSEXP, SEXP NSEXP, SEXP return_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<IntegerVector> >::type estimation(estimationSEXP);
    Rcpp::traits::input_parameter< arma::field<IntegerVector> >::type truth(truthSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< bool >::type return_matrix(return_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(evaluate_performance(estimation, truth, N, return_matrix));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_chomper_EvolutionaryVI", (DL_FUNC) &_chomper_EvolutionaryVI, 29},
    {"_chomper_MCMC", (DL_FUNC) &_chomper_MCMC, 24},
    {"_chomper_CoordinateAscentVI", (DL_FUNC) &_chomper_CoordinateAscentVI, 24},
    {"_chomper_DIG", (DL_FUNC) &_chomper_DIG, 23},
    {"_chomper_psm_vi", (DL_FUNC) &_chomper_psm_vi, 1},
    {"_chomper_psm_mcmc", (DL_FUNC) &_chomper_psm_mcmc, 1},
    {"_chomper_flatten_posterior_samples", (DL_FUNC) &_chomper_flatten_posterior_samples, 3},
    {"_chomper_evaluate_performance", (DL_FUNC) &_chomper_evaluate_performance, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_chomper(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
