#' Italian Survey on Household Income and Wealth (ISHIW) data from 2020 and 2022
#'
#' Two data files collected in 2020 and 2022 surveys.
#' Totally 38,255 records from 28,000 participants exist across two survey.
#' Categorical variables are recorded with integers, and continuous variables are standardized to have a mean of 0 and a variance of 1.
#'
#' @format A list of matrices with 9 variables. 15,198 rows and 23,057 rows are contained in surveys in 2020 and 2022, respectively.
#' \describe{
#'   \item{ID}{Unique ID of each entity}
#'   \item{SEX}{sex}
#'   \item{ANASC}{year of birth}
#'   \item{CIT}{nationality (whether or not Italian)}
#'   \item{NASCREG}{administrative region of birth}
#'   \item{STUDIO}{education level}
#'   \item{IREG}{administrative region of current residence}
#'   \item{NETINCOME}{net income}
#'   \item{VALABIT}{estimated price of residence}
#' }
#' @source \url{https://www.bancaditalia.it/statistiche/tematiche/indagini-famiglie-imprese/bilanci-famiglie/distribuzione-microdati/index.html}
"italy"

#' Synthetic data with high overlap ratio (70%)
#'
#' A synthetic data to illustrate the functionality of \code{chomper} model.
#' A list contains 2 matrices to perform entity resolution, and records are generated with 750 unique entities.
#' Each file contains 8 variables including unique id and 646 and 629 records, respectively.
#' Categorical variables are recorded with integers, and continuous variables are standardized to have a mean of 0 and a variance of 1.
#'
#' @format A list of matrices with 8 variables. 646 rows and 629 rows are contained in data, respectively.
#' \describe{
#'   \item{id}{Unique ID of each entity}
#'   \item{X01}{categorical variable with a single truth of 8 levels}
#'   \item{X02}{categorical variable with a single truth of 8 levels}
#'   \item{X03}{categorical variable with a single truth of 8 levels}
#'   \item{X04}{categorical variable with 1-adjacent multiple truths of 8 levels}
#'   \item{X05}{categorical variable with 1-adjacent multiple truths of 8 levels}
#'   \item{X06}{continuous variable with multiple truths}
#'   \item{X07}{continuous variable with multiple truths}
#' }
#' @source Generated by the package authors. Authors used \code{generate_sample_data} function in \code{R/generate_sample_data.R}.
"simulation.high"

#' Synthetic data with medium overlap ratio (50%)
#'
#' A synthetic data to illustrate the functionality of \code{chomper} model.
#' A list contains 2 matrices to perform entity resolution, and records are generated with 750 unique entities.
#' Each file contains 8 variables including unique id and 569 and 556 records, respectively.
#' Categorical variables are recorded with integers, and continuous variables are standardized to have a mean of 0 and a variance of 1.
#'
#' @format A list of matrices with 8 variables. 569 rows and 556 rows are contained in data, respectively.
#' \describe{
#'   \item{id}{Unique ID of each entity}
#'   \item{X01}{categorical variable with a single truth of 8 levels}
#'   \item{X02}{categorical variable with a single truth of 8 levels}
#'   \item{X03}{categorical variable with a single truth of 8 levels}
#'   \item{X04}{categorical variable with 1-adjacent multiple truths of 8 levels}
#'   \item{X05}{categorical variable with 1-adjacent multiple truths of 8 levels}
#'   \item{X06}{continuous variable with multiple truths}
#'   \item{X07}{continuous variable with multiple truths}
#' }
#' @source Generated by the package authors. Authors used \code{generate_sample_data} function in \code{R/generate_sample_data.R}.
"simulation.medium"

#' Synthetic data with low overlap ratio (30%)
#'
#' A synthetic data to illustrate the functionality of \code{chomper} model.
#' A list contains 2 matrices to perform entity resolution, and records are generated with 750 unique entities.
#' Each file contains 8 variables including unique id and 478 and 497 records, respectively.
#' Categorical variables are recorded with integers, and continuous variables are standardized to have a mean of 0 and a variance of 1.
#'
#' @format A list of matrices with 8 variables. 478 rows and 497 rows are contained in data, respectively.
#' \describe{
#'   \item{id}{Unique ID of each entity}
#'   \item{X01}{categorical variable with a single truth of 8 levels}
#'   \item{X02}{categorical variable with a single truth of 8 levels}
#'   \item{X03}{categorical variable with a single truth of 8 levels}
#'   \item{X04}{categorical variable with 1-adjacent multiple truths of 8 levels}
#'   \item{X05}{categorical variable with 1-adjacent multiple truths of 8 levels}
#'   \item{X06}{continuous variable with multiple truths}
#'   \item{X07}{continuous variable with multiple truths}
#' }
#' @source Generated by the package authors. Authors used \code{generate_sample_data} function in \code{R/generate_sample_data.R}.
"simulation.low"
