# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.EvolutionaryVI <- function(x, k, n, N, p, discrete_fields, n_discrete_fields, M, continuous_fields, n_continuous_fields, hyper_beta, hyper_sigma, hyper_phi, hyper_tau, hyper_delta, overlap_prob, n_parents, n_children, tol_cavi, max_iter_cavi, tol_evi, max_iter_evi, verbose, n_threads, max_time, custom_initializer, use_checkpoint, initial_values, checkpoint_values) {
    .Call(`_chomper_EvolutionaryVI`, x, k, n, N, p, discrete_fields, n_discrete_fields, M, continuous_fields, n_continuous_fields, hyper_beta, hyper_sigma, hyper_phi, hyper_tau, hyper_delta, overlap_prob, n_parents, n_children, tol_cavi, max_iter_cavi, tol_evi, max_iter_evi, verbose, n_threads, max_time, custom_initializer, use_checkpoint, initial_values, checkpoint_values)
}

.MCMC <- function(x, k, n, N, p, discrete_fields, n_discrete_fields, M, continuous_fields, n_continuous_fields, hyper_beta, hyper_sigma, hyper_phi, hyper_tau, hyper_delta, n_burnin, n_gibbs, n_split_merge, max_time, custom_initializer, use_checkpoint, initial_values, checkpoint_values) {
    .Call(`_chomper_MCMC`, x, k, n, N, p, discrete_fields, n_discrete_fields, M, continuous_fields, n_continuous_fields, hyper_beta, hyper_sigma, hyper_phi, hyper_tau, hyper_delta, n_burnin, n_gibbs, n_split_merge, max_time, custom_initializer, use_checkpoint, initial_values, checkpoint_values)
}

.CoordinateAscentVI <- function(x, k, n, N, p, discrete_fields, n_discrete_fields, M, continuous_fields, n_continuous_fields, hyper_beta, hyper_sigma, hyper_phi, hyper_tau, hyper_delta, overlap_prob, tol_cavi, max_iter_cavi, verbose, max_time, custom_initializer, use_checkpoint, initial_values, checkpoint_values) {
    .Call(`_chomper_CoordinateAscentVI`, x, k, n, N, p, discrete_fields, n_discrete_fields, M, continuous_fields, n_continuous_fields, hyper_beta, hyper_sigma, hyper_phi, hyper_tau, hyper_delta, overlap_prob, tol_cavi, max_iter_cavi, verbose, max_time, custom_initializer, use_checkpoint, initial_values, checkpoint_values)
}

.psm_vi <- function(probs_field) {
    .Call(`_chomper_psm_vi`, probs_field)
}

.psm_mcmc <- function(samples) {
    .Call(`_chomper_psm_mcmc`, samples)
}

.flatten_posterior_samples <- function(samples, k, N) {
    .Call(`_chomper_flatten_posterior_samples`, samples, k, N)
}

.evaluate_performance <- function(estimation, truth, N, return_matrix) {
    .Call(`_chomper_evaluate_performance`, estimation, truth, N, return_matrix)
}

